version: '3'
services:
  vectordb:
    image: qdrant/qdrant
    container_name: vectordb
    ports:
      - 6333:6333
  clipservice:
    image: supervisely/cas
    container_name: clipservice
    ports:
      - 51000:51000