FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
    
RUN pip install clip-server==0.8.3

CMD ["python3", "-m", "clip_server"]